import { createClient } from '@/lib/supabase';
import { requireMembership } from '@/lib/auth';
import { JURISDICTION_BY_KEY } from '@/lib/taxonomy';
import { formatDate } from '@/lib/utils';

export default async function SourcesPage() {
  await requireMembership();
  const supabase = await createClient();

  const { data: sources } = await supabase
    .from('legal_sources')
    .select('id, key, title, jurisdiction, sector, source_type, language, effective_from, effective_to, official_url, ingested_at')
    .order('jurisdiction', { ascending: true })
    .order('title', { ascending: true });

  const grouped = (sources ?? []).reduce<Record<string, typeof sources>>((acc, s) => {
    (acc[s.jurisdiction] ??= []).push(s);
    return acc;
  }, {});

  return (
    <div className="p-8">
      <h1 className="text-2xl font-semibold mb-2" style={{ fontFamily: 'var(--font-playfair), Georgia, serif' }}>
        Legal corpus
      </h1>
      <p className="text-sm mb-8" style={{ color: '#6b7280' }}>
        Primary-source statutes, regulations and standards available for retrieval. Every clause
        generated by LEXAI must cite at least one row from this corpus.
      </p>

      {Object.keys(grouped).length === 0 && (
        <div className="p-10 rounded-md text-center" style={{ border: '1px dashed #d4d4d4', color: '#6b7280' }}>
          No sources ingested yet. Run the ingestion pipeline (Phase 1) — start with
          <code className="px-1.5 py-0.5 rounded" style={{ backgroundColor: '#ececec' }}>
            bun run ingest -- --jurisdiction=ae:difc
          </code>
          .
        </div>
      )}

      {Object.entries(grouped).map(([jurisdiction, items]) => (
        <section key={jurisdiction} className="mb-10">
          <h2 className="text-sm uppercase tracking-widest mb-3" style={{ color: '#111111' }}>
            {JURISDICTION_BY_KEY.get(jurisdiction)?.label ?? jurisdiction}
          </h2>
          <div className="grid gap-2">
            {(items ?? []).map((s) => (
              <div
                key={s.id}
                className="p-3 rounded-md border flex items-center justify-between"
                style={{ borderColor: '#ececec', backgroundColor: '#fafaf9' }}
              >
                <div>
                  <div className="text-sm font-medium">{s.title}</div>
                  <div className="text-xs mt-1" style={{ color: '#6b7280' }}>
                    {s.source_type} · {s.language?.toUpperCase()}
                    {s.effective_from && ` · in force from ${formatDate(s.effective_from)}`}
                    {s.effective_to && ` (superseded ${formatDate(s.effective_to)})`}
                  </div>
                </div>
                <div className="text-xs" style={{ color: '#111111' }}>
                  {s.ingested_at ? `ingested ${formatDate(s.ingested_at)}` : 'not ingested'}
                </div>
              </div>
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}
